package vista;

import javax.swing.JOptionPane;
import control.GestionInicioSesion;

/**
 *
 * @author Estudiante
 */
public class Login extends javax.swing.JFrame {

    boolean userIn = false;
    GestionInicioSesion sesion;
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        sesion = new GestionInicioSesion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jB_Salir = new javax.swing.JButton();
        jPassword_Contraseña = new javax.swing.JPasswordField();
        jB_IniciarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jText_Usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_Salir.setBackground(new java.awt.Color(204, 204, 255));
        jB_Salir.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jB_Salir.setText("Salir");
        jB_Salir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jB_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jB_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 80, -1));

        jPassword_Contraseña.setBackground(new java.awt.Color(204, 204, 255));
        jPassword_Contraseña.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jPassword_Contraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPassword_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword_ContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 110, 30));

        jB_IniciarSesion.setBackground(new java.awt.Color(204, 204, 255));
        jB_IniciarSesion.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jB_IniciarSesion.setText("Iniciar Sesión");
        jB_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_IniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jB_IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 140, 150));

        jText_Usuario.setBackground(new java.awt.Color(204, 204, 255));
        jText_Usuario.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jText_Usuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jText_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jText_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 110, 30));

        jLabel4.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 120, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jB_SalirActionPerformed

    private void jText_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_UsuarioActionPerformed

    private void jPassword_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword_ContraseñaActionPerformed

    private void jB_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_IniciarSesionActionPerformed
        String id = jText_Usuario.getText();
        String contraseña = jPassword_Contraseña.getText();

        if (id.isEmpty() || contraseña.isEmpty()) { //Método que devuelve true en el caso de que el tamaño de la cadena sera 0. En otro caso devuelve false.
            JOptionPane.showMessageDialog(null, "Algun espacio esta vacio");
        } else {
            if (id.equals("admin") && contraseña.equals("123456")) { //condicionamos el inicio de id y contraseña
                JOptionPane.showMessageDialog(null, "BIENVENIDO ADMINISTRADOR:");
                vistaTienda panel = new vistaTienda();// se llama el panel a que se va ingresar con un objeto
                panel.setVisible(true);//visibilidad del panel
                dispose();
                userIn = true;
                sesion.verificarLogin(userIn);
            } else if (id.equals("user") && contraseña.equals("123456")) { //condicionamos el inicio de id y contraseña
                JOptionPane.showMessageDialog(null, "BIENVENIDO Usuario:");
                vistaTienda panel = new vistaTienda();// se llama el panel a que se va ingresar con un objeto
                panel.setVisible(true);//visibilidad del panel
                dispose();
                userIn = false;
                sesion.verificarLogin(userIn);
            }
        }
    }//GEN-LAST:event_jB_IniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_IniciarSesion;
    private javax.swing.JButton jB_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPassword_Contraseña;
    private javax.swing.JTextField jText_Usuario;
    // End of variables declaration//GEN-END:variables

}
